services:
  app:
    build: .
    container_name: learningflow_app
    env_file:
      - .env
    ports:
      - "${HTTP_PORT:-8080}":"${HTTP_PORT:-8080}"
    depends_on:
      - postgres:
          condition: service_healthy
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5